"""
Generates a 16x16, 4-direction x 2-frame walking spritesheet for the
protagonist, hand-drawn pixel by pixel (rectangles) in a limited
SNES/FC-era JRPG palette, based on the reference character art
(black spiky hair, black kimono-style gi with blue trim, gray sash,
black hakama pants, chain weapon).

"left" is generated by mirroring the "right" frame (never drawn twice
by hand), so the two stay visually consistent.

Output: assets/sprites/hero_walk.png
Layout: 4 columns (down, left, right, up) x 2 rows (frame A, frame B)
        each cell 16x16 -> sheet is 64x32
"""
from PIL import Image

TILE = 16
COLS = 4   # down, left, right, up
ROWS = 2   # frame a, frame b

HAIR = (26, 24, 30, 255)
SKIN = (240, 198, 160, 255)
SKIN_SHADE = (214, 168, 130, 255)
OUTFIT = (22, 22, 27, 255)
TRIM = (58, 92, 200, 255)
SASH = (150, 150, 162, 255)
SASH_SHADE = (120, 120, 132, 255)
SHOE = (12, 12, 15, 255)
EYE = (12, 12, 14, 255)
EMBLEM = (222, 222, 232, 255)
CHAIN = (176, 176, 186, 255)


def blank():
    return Image.new("RGBA", (TILE, TILE), (0, 0, 0, 0))


def rect(img, x0, y0, x1, y1, color):
    d = img.load()
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            if 0 <= x < TILE and 0 <= y < TILE:
                d[x, y] = color


def dot(img, x, y, color):
    if 0 <= x < TILE and 0 <= y < TILE:
        img.load()[x, y] = color


def draw_head(img, facing):
    rect(img, 5, 0, 10, 1, HAIR)
    rect(img, 4, 1, 11, 2, HAIR)
    dot(img, 3, 1, HAIR)
    dot(img, 12, 1, HAIR)
    dot(img, 6, 0, HAIR)
    dot(img, 9, 0, HAIR)
    rect(img, 4, 3, 4, 6, HAIR)
    rect(img, 11, 3, 11, 6, HAIR)

    if facing == "up":
        rect(img, 5, 2, 10, 6, HAIR)
        return

    rect(img, 5, 3, 10, 6, SKIN)
    if facing == "down":
        dot(img, 6, 5, EYE)
        dot(img, 9, 5, EYE)
    elif facing == "right":
        dot(img, 9, 5, EYE)
        rect(img, 4, 3, 5, 6, HAIR)


def draw_torso(img, facing, step):
    rect(img, 6, 7, 9, 7, HAIR if facing == "up" else SKIN_SHADE)
    rect(img, 4, 8, 11, 11, OUTFIT)
    rect(img, 4, 8, 4, 11, TRIM)
    rect(img, 11, 8, 11, 11, TRIM)
    if facing in ("down", "up"):
        rect(img, 6, 8, 9, 8, TRIM)
        if facing == "down":
            dot(img, 8, 9, EMBLEM)
    rect(img, 4, 10, 11, 10, SASH)
    dot(img, 7, 10, SASH_SHADE)
    dot(img, 8, 10, SASH_SHADE)
    if facing == "right" and step == 0:
        dot(img, 12, 9, CHAIN)
        dot(img, 12, 10, CHAIN)


def draw_legs(img, facing, step):
    rect(img, 5, 12, 10, 13, OUTFIT)
    if facing in ("down", "up"):
        if step == 0:
            rect(img, 5, 14, 7, 15, SHOE)
            rect(img, 8, 14, 10, 15, SHOE)
        else:
            rect(img, 4, 14, 6, 15, SHOE)
            rect(img, 9, 14, 11, 15, SHOE)
    else:
        if step == 0:
            rect(img, 4, 14, 6, 15, SHOE)
            rect(img, 8, 13, 10, 15, SHOE)
        else:
            rect(img, 8, 14, 10, 15, SHOE)
            rect(img, 4, 13, 6, 15, SHOE)


def build_frame(facing, step):
    img = blank()
    draw_head(img, facing)
    draw_torso(img, facing, step)
    draw_legs(img, facing, step)
    return img


def main():
    sheet = Image.new("RGBA", (TILE * COLS, TILE * ROWS), (0, 0, 0, 0))
    order = ["down", "left", "right", "up"]
    for col, facing in enumerate(order):
        for row, step in enumerate([0, 1]):
            if facing == "left":
                frame = build_frame("right", step).transpose(Image.FLIP_LEFT_RIGHT)
            else:
                frame = build_frame(facing, step)
            sheet.paste(frame, (col * TILE, row * TILE), frame)
    out = "assets/sprites/hero_walk.png"
    sheet.save(out)
    print("saved", out, sheet.size)


if __name__ == "__main__":
    main()
